trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build'
      artifactName: 'drop'
trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Build and Publish'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
